# -*- mode: ruby -*-
# vi: set ft=ruby :

path_prefix = "C:/";
share_user = "www-data"

# server configuration
vm_ip_address = "192.168.56.203"
vm_name = "omicron-web03"
repo = path_prefix + "git"


Vagrant.configure("2") do |config|

    config.vm.box = "debian/stretch64"

    config.vm.network "private_network", ip: vm_ip_address
    config.vm.hostname = vm_name

    config.vm.synced_folder '../', "/vagrant-base",owner: "vagrant", group: "vagrant"
    config.vm.synced_folder "#{repo}/", "/mnt/repo", owner:"#{share_user}", group:"www-data"
    #config.vm.synced_folder '../', "/vagrant-base",owner: "vagrant", group: "vagrant"

    # provisioning
    config.vm.provision :shell, path: "provisioners/bootstrap.sh"

    #config.vm.provision :shell, path: "provisioners/vhosts.sh"

end