# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "prosper"

  config.vm.network "private_network", ip: "192.168.56.150"

  config.ssh.username = "root"
  config.ssh.password = "NSN!root"
end
